apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui	
spec:	
  type: NodePort
  ports:	
  - name: http-guestbook-ui
    port: 18034
    targetPort: 80
    protocol: TCP
  selector:	
    app: guestbook-ui
